<a href="https://colab.research.google.com/github/ramiltrinidad-ctrl/maida/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
numpy as np

SyntaxError: invalid syntax (3349220584.py, line 1)

In [66]:
import numpy as np

In [65]:
import matplotlib.pyplot as plt

In [64]:
import pandas_datareader.data as web

In [63]:
import yfinance as yf

In [40]:
population = np.array([38000000, 12000000, 8000000, 7899998, 9768234])
area = np.array([123456, 78901, 23456, 877673, 98726])

In [31]:
obj.index = ['qwe','yhrtder', 'wkjashd']

In [30]:
obj = pd.Series(['California', 'Mexico', 'Los Angeles'])
obj.index = ['qwe','yhrtder', 'wkjashd']

In [38]:
pd.Index(['a','b','c','d', 'e'], dtype='object')

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [41]:
pd.Index

pandas.core.indexes.base.Index

In [42]:
states = pd.DataFrame({'population': population, 'area': area})

states

   population    area
0    38000000  123456
1    12000000   78901
2     8000000   23456
3     7899998  877673
4     9768234   98726

In [43]:
display(states)

   population    area
0    38000000  123456
1    12000000   78901
2     8000000   23456
3     7899998  877673
4     9768234   98726

In [44]:
states.T

                   0         1        2        3        4
population  38000000  12000000  8000000  7899998  9768234
area          123456     78901    23456   877673    98726

In [46]:
states.iloc[:5, :5]

   population    area
0    38000000  123456
1    12000000   78901
2     8000000   23456
3     7899998  877673
4     9768234   98726

In [47]:
states.index = ['California', 'Texas', 'New York', 'Florida', 'Pennsylvania']
display(states)

              population    area
California      38000000  123456
Texas           12000000   78901
New York         8000000   23456
Florida          7899998  877673
Pennsylvania     9768234   98726

In [49]:
# Calculate the 'density' column
states['density'] = states['population'] / states['area']
display(states.head())

              population    area     density
California      38000000  123456  307.801970
Texas           12000000   78901  152.089327
New York         8000000   23456  341.064120
Florida          7899998  877673    9.001072
Pennsylvania     9768234   98726   98.942872

In [50]:
# Now, re-run the original operation
states[states.density > 100]['population'] = 100
display(states)

/tmp/ipykernel_13452/326927017.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  states[states.density > 100]['population'] = 100

              population    area     density
California      38000000  123456  307.801970
Texas           12000000   78901  152.089327
New York         8000000   23456  341.064120
Florida          7899998  877673    9.001072
Pennsylvania     9768234   98726   98.942872

In [52]:
states[states.density > 100]['population'] = 100

/tmp/ipykernel_13452/474393611.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  states[states.density > 100]['population'] = 100

In [57]:
obj = pd.Series([4.5, -7.2, -5.3, 3.6], index=['d','a','b','c'])
display(obj)

d    4.5
a   -7.2
b   -5.3
c    3.6
dtype: float64

In [58]:
obj

d    4.5
a   -7.2
b   -5.3
c    3.6
dtype: float64

In [59]:
obj.drop(['a'])

d    4.5
b   -5.3
c    3.6
dtype: float64

In [60]:
index_names = ['^GSPC', '^DJI', '^IXIC', '^RUT']

In [61]:
start_date_string = "2018-01-01"
end_date_string = "2022-04-21"

In [68]:
raw_data = yf.download(index_names, start=start_date_string, end=end_date_string)

/tmp/ipykernel_13452/1862392190.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  raw_data = yf.download(index_names, start=start_date_string, end=end_date_string)
[*********************100%***********************]  4 of 4 completed

In [69]:
data

NameError: name 'data' is not defined

In [72]:
raw_data

Price              Close                                          \
Ticker              ^DJI        ^GSPC         ^IXIC         ^RUT
Date
2018-01-02  24824.009766  2695.810059   7006.899902  1550.010010
2018-01-03  24922.679688  2713.060059   7065.529785  1552.579956
2018-01-04  25075.130859  2723.989990   7077.910156  1555.719971
2018-01-05  25295.869141  2743.149902   7136.560059  1560.010010
2018-01-08  25283.000000  2747.709961   7157.390137  1561.810059
...                  ...          ...           ...          ...
2022-04-13  34564.589844  4446.589844  13643.589844  2025.099976
2022-04-14  34451.230469  4392.589844  13351.080078  2004.979980
2022-04-18  34411.691406  4391.689941  13332.360352  1990.130005
2022-04-19  34911.199219  4462.209961  13619.660156  2030.770020
2022-04-20  35160.789062  4459.450195  13453.070312  2038.189941

Price               High                                          \
Ticker              ^DJI        ^GSPC         ^IXIC         ^RUT
Date
2018-01-02  24864.189453  2695.889893   7006.910156  1550.300049
2018-01-03  24941.919922  2714.370117   7069.149902  1555.079956
2018-01-04  25105.960938  2729.290039   7098.049805  1560.839966
2018-01-05  25299.789062  2743.449951   7137.040039  1560.069946
2018-01-08  25311.990234  2748.510010   7161.350098  1562.989990
...                  ...          ...           ...          ...
2022-04-13  34598.359375  4453.919922  13679.429688  2028.790039
2022-04-14  34889.171875  4460.459961  13662.929688  2034.219971
2022-04-18  34618.289062  4410.310059  13414.269531  2003.270020
2022-04-19  34983.109375  4471.029785  13643.969727  2035.790039
2022-04-20  35315.398438  4488.290039  13678.549805  2052.080078

Price                Low                                          \
Ticker              ^DJI        ^GSPC         ^IXIC         ^RUT
Date
2018-01-02  24741.699219  2682.360107   6924.080078  1536.119995
2018-01-03  24825.550781  2697.770020   7016.700195  1547.589966
2018-01-04  24963.269531  2719.070068   7072.379883  1552.369995
2018-01-05  25112.009766  2727.919922   7097.080078  1552.130005
2018-01-08  25235.410156  2737.600098   7124.089844  1548.229980
...                  ...          ...           ...          ...
2022-04-13  34140.640625  4392.700195  13353.660156  1987.329956
2022-04-14  34437.500000  4390.770020  13345.219727  2004.969971
2022-04-18  34279.078125  4370.299805  13222.030273  1981.689941
2022-04-19  34394.621094  4390.629883  13281.219727  1990.209961
2022-04-20  34962.671875  4448.759766  13426.129883  2032.390015

Price               Open                                             Volume  \
Ticker              ^DJI        ^GSPC         ^IXIC         ^RUT       ^DJI
Date
2018-01-02  24809.349609  2683.729980   6937.649902  1536.119995  341130000
2018-01-03  24850.449219  2697.850098   7017.069824  1550.280029  456790000
2018-01-04  24964.859375  2719.310059   7089.500000  1552.979980  403280000
2018-01-05  25114.919922  2731.330078   7105.740234  1555.869995  358020000
2018-01-08  25308.400391  2742.669922   7135.379883  1559.800049  341390000
...                  ...          ...           ...          ...        ...
2022-04-13  34166.640625  4394.299805  13373.120117  1987.329956  313630000
2022-04-14  34628.460938  4449.120117  13647.429688  2025.170044  353680000
2022-04-18  34411.488281  4385.629883  13319.389648  2003.270020  264110000
2022-04-19  34394.621094  4390.629883  13312.440430  1990.209961  296350000
2022-04-20  34962.671875  4472.259766  13665.379883  2032.390015  337620000

Price
Ticker           ^GSPC       ^IXIC        ^RUT
Date
2018-01-02  3397430000  1929700000  3397430000
2018-01-03  3544030000  2173130000  3544030000
2018-01-04  3697340000  2103220000  3697340000
2018-01-05  3239280000  2024000000  3239280000
2018-01-08  3246160000  2055010000  3246160000
...                ...         ...         ...
2022-04-13  3828150000  4909720000  3828150000
2022-04-14  4083090000  4642240000  4083090000
2022-04-18  3910490000  4365230000  3910490000
2022-04-19  4108120000  4562840000  4108120000
2022-04-20  4290450000  4678930000  4290450000

[1083 rows x 20 columns]

In [73]:
np.random.seed(1337)
data = pd.DataFrame({'user_id': ['001', '002', '023'],
                     'milk': [0, 1, 2],
                     'cheese': [0, 0, 1],
                     'diaper': [1, 0, 1],
                     'beer': [1, 1, 0]}).set_index('user_id')
data.columns.name = 'product'
data

product  milk  cheese  diaper  beer
user_id
001         0       0       1     1
002         1       0       0     1
023         2       1       1     0

In [74]:
incoming_data = pd.DataFrame({'user_id': ['001', '002', '007'],
                              'chips': [1, 1, 1],
                              'diaper': [0, 0, 1],
                              'beer': [1, 0, 1]}).set_index('user_id')

incoming_data

         chips  diaper  beer
user_id
001          1       0     1
002          1       0     0
007          1       1     1

In [75]:
data + incoming_data

         beer  cheese  chips  diaper  milk
user_id
001       2.0     NaN    NaN     1.0   NaN
002       1.0     NaN    NaN     0.0   NaN
007       NaN     NaN    NaN     NaN   NaN
023       NaN     NaN    NaN     NaN   NaN

In [76]:
updated_data = data.add(incoming_data, fill_value=0).fillna(-999)
updated_data

         beer  cheese  chips  diaper   milk
user_id
001       2.0     0.0    1.0     1.0    0.0
002       1.0     0.0    1.0     0.0    1.0
007       1.0  -999.0    1.0     1.0 -999.0
023       0.0     1.0 -999.0     1.0    2.0

In [79]:
one_bucket_for_everybody = pd.Series({'beer': 5})
one_bucket_for_everybody

beer    5
dtype: int64

In [82]:
updated_data.add(
    pd.DataFrame(5, index=updated_data.index, columns=['beer']),
    fill_value=0
)

         beer  cheese  chips  diaper   milk
user_id
001       7.0     0.0    1.0     1.0    0.0
002       6.0     0.0    1.0     0.0    1.0
007       6.0  -999.0    1.0     1.0 -999.0
023       5.0     1.0 -999.0     1.0    2.0

In [89]:
updated_data['beer'] += 100
updated_data

          beer  cheese  chips  diaper   milk
user_id
001      110.0     0.0    1.0     1.0    0.0
002      109.0     0.0    1.0     0.0    1.0
007      109.0  -999.0    1.0     1.0 -999.0
023      108.0     1.0 -999.0     1.0    2.0

In [90]:
np.sign(updated_data)

         beer  cheese  chips  diaper  milk
user_id
001       1.0     0.0    1.0     1.0   0.0
002       1.0     0.0    1.0     0.0   1.0
007       1.0    -1.0    1.0     1.0  -1.0
023       1.0     1.0   -1.0     1.0   1.0

In [91]:
np.square(updated_data)

            beer    cheese     chips  diaper      milk
user_id
001      12100.0       0.0       1.0     1.0       0.0
002      11881.0       0.0       1.0     0.0       1.0
007      11881.0  998001.0       1.0     1.0  998001.0
023      11664.0       1.0  998001.0     1.0       4.0

In [94]:
def range_value(x):
  return x.max() - x.min()

display(range_value(updated_data['beer']))

2.0

In [97]:
def maxmin_diff(x):
  return x.max() - x.min()

display(range_value(updated_data['beer']))

2.0

In [98]:
updated_data.apply(maxmin_diff)

beer         2.0
cheese    1000.0
chips     1000.0
diaper       1.0
milk      1001.0
dtype: float64

In [99]:
updated_data.apply(maxmin_diff, axis='columns')

user_id
001     110.0
002     109.0
007    1108.0
023    1107.0
dtype: float64

In [100]:
def min_max_mean(x):
    return pd.Series(
        [x.min(), x.max(), x.mean()],
        index=['min', 'max', 'mean']
    )

updated_data.apply(min_max_mean)

       beer  cheese  chips  diaper   milk
min   108.0  -999.0 -999.0    0.00 -999.0
max   110.0     1.0    1.0    1.00    2.0
mean  109.0  -249.5 -249.0    0.75 -249.0

In [101]:
updated_data.apply(min_max_mean, axis=1)

           min    max   mean
user_id
001        0.0  110.0   22.4
002        0.0  109.0   22.2
007     -999.0  109.0 -377.4
023     -999.0  108.0 -177.4

In [102]:
updated_data

          beer  cheese  chips  diaper   milk
user_id
001      110.0     0.0    1.0     1.0    0.0
002      109.0     0.0    1.0     0.0    1.0
007      109.0  -999.0    1.0     1.0 -999.0
023      108.0     1.0 -999.0     1.0    2.0

In [103]:
updated_data.map(int)

         beer  cheese  chips  diaper  milk
user_id
001       110       0      1       1     0
002       109       0      1       0     1
007       109    -999      1       1  -999
023       108       1   -999       1     2

In [105]:
def sq_num(x):
  return x**2

In [106]:
updated_data.map(sq_num)

            beer    cheese     chips  diaper      milk
user_id
001      12100.0       0.0       1.0     1.0       0.0
002      11881.0       0.0       1.0     0.0       1.0
007      11881.0  998001.0       1.0     1.0  998001.0
023      11664.0       1.0  998001.0     1.0       4.0

In [107]:
updated_data['beer'].map(sq_num)

user_id
001    12100.0
002    11881.0
007    11881.0
023    11664.0
Name: beer, dtype: float64

In [108]:
updated_data

          beer  cheese  chips  diaper   milk
user_id
001      110.0     0.0    1.0     1.0    0.0
002      109.0     0.0    1.0     0.0    1.0
007      109.0  -999.0    1.0     1.0 -999.0
023      108.0     1.0 -999.0     1.0    2.0

In [109]:
updated_data

          beer  cheese  chips  diaper   milk
user_id
001      110.0     0.0    1.0     1.0    0.0
002      109.0     0.0    1.0     0.0    1.0
007      109.0  -999.0    1.0     1.0 -999.0
023      108.0     1.0 -999.0     1.0    2.0

In [110]:
updated_data.sort_index(axis='columns', ascending=False)

          milk  diaper  chips  cheese   beer
user_id
001        0.0     1.0    1.0     0.0  110.0
002        1.0     0.0    1.0     0.0  109.0
007     -999.0     1.0    1.0  -999.0  109.0
023        2.0     1.0 -999.0     1.0  108.0

In [111]:
updated_data.milk.sort_values()

user_id
007   -999.0
001      0.0
002      1.0
023      2.0
Name: milk, dtype: float64

In [112]:
updated_data.sort_values(by='milk')

          beer  cheese  chips  diaper   milk
user_id
007      109.0  -999.0    1.0     1.0 -999.0
001      110.0     0.0    1.0     1.0    0.0
002      109.0     0.0    1.0     0.0    1.0
023      108.0     1.0 -999.0     1.0    2.0

In [113]:
updated_data.index

Index(['001', '002', '007', '023'], dtype='object', name='user_id')

In [117]:
incoming_data2 = pd.DataFrame({'user_id': ['001', '002', '254'],
                               'chips': [1, 1, 1],
                               'iewruyg': [0, 0, 1],
                               'beer': [1, 0, 1]}).set_index('user_id')

In [115]:
incoming_data2

         chips  iewruyg  beer
user_id
001          1        0     1
002          1        0     0
254          1        1     1

In [118]:
incoming_data2.sort_index()

         chips  iewruyg  beer
user_id
001          1        0     1
002          1        0     0
254          1        1     1

In [120]:
updated_data.rank()

         beer  cheese  chips  diaper  milk
user_id
001       4.0     2.5    3.0     3.0   2.0
002       2.5     2.5    3.0     1.0   3.0
007       2.5     1.0    3.0     3.0   1.0
023       1.0     4.0    1.0     3.0   4.0